apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-test-job
  namespace: fiapx
spec:
  template:
    spec:
      containers:
      - name: e2e-test
        image: alpine:3.19
        command: ["/bin/sh", "/scripts/e2e-test-internal.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        env:
        - name: KONG_URL
          value: "http://kong:8000"
      volumes:
      - name: scripts
        configMap:
          name: infra-scripts
          defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 0
