apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: fiapx
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE video_db;
    CREATE DATABASE notification_db;
    CREATE DATABASE kong_db;
